version: '3.9'
services:
  db:
    image: mysql:8.0.20
    restart: always
    environment:
      MYSQL_DATABASE: 'Spectrum'
      MYSQL_USER: 'kotiks'
      MYSQL_PASSWORD: 'mew'
      MYSQL_ROOT_PASSWORD: 'mew'
    ports:
      - '3306:3306'
    expose:
      - '3306'